theme: plainwhite

remote_theme: samarsault/plainwhite-jekyll

title: S. Galiamov blog
author: sgaliamov
email: 6alyamov@gmail.com
description: S. Galiamov blog.
show_excerpts: true

plainwhite:
  name: Salavat Galiamov
  portfolio_image: "assets/yagami.png"
  html_lang: "en"
  disqus_shortname: sgaliamov
  sitemap: true
  search: true
  show_excerpts: true
  dark_mode: true

  social_links:
    github: sgaliamov
    linkedIn: in/sgaliamov

  tagline: |
    yet another
    developer

plugins:
  - jekyll-seo-tag
