theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
title: S. Galiamov
author: sgaliamov
email: 6alyamov@gmail.com
show_excerpts: true
baseurl: /blog

plainwhite:
  name: Salavat Galiamov
  portfolio_image: "assets/yagami.png"
  html_lang: "en"
  disqus_shortname: sgaliamov
  sitemap: true
  dark_mode: true
  social_links:
    github: sgaliamov
    linkedIn: in/sgaliamov
  navigation:
    - title: Pluralsight courses reviews
      url: "https://sgaliamov.github.io/blog/pages/pluralsight.html"
    - title: medium.com
      url: "https://sgaliamov.medium.com/"

  tagline: |
    yet another
    developer

plugins:
  - jekyll-seo-tag
