theme: plainwhite

remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Salavat Galiamov
  tagline: yet another developer
  portfolio_image: "assets/yagami.png"
  html_lang: "en"
  disqus_shortname: sgaliamov
  social_links:
    github: sgaliamov
    linkedIn: in/sgaliamov

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
