theme: plainwhite

remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Salavat Galiamov
  tagline: yet another developer
  portfolio_image: "assets/yagami.png"
  html_lang: "en"
  disqus_shortname: sgaliamov
  sitemap: true
  search: true

  social_links:
    github: sgaliamov
    linkedIn: in/sgaliamov

  tagline: |
    First Line.
    Second Line.
    Third Line.

plugins:
  - jekyll-seo-tag
